import { useEffect, useState, type FormEvent } from 'react';
import { useLocation } from 'wouter';
import { PageShell } from '../components/PageShell';
import { RoutePlannerMap } from '../components/RoutePlannerMap';
import { useSession } from '../lib/auth';
import type { Difficulty, RoutePoint } from '../lib/cyclingModels';
import { createRoute, routeDistanceKm } from '../lib/routes';

export function NewRoutePage() {
  const { session, loading } = useSession(); const [, navigate] = useLocation(); const [points, setPoints] = useState<RoutePoint[]>([]); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [region, setRegion] = useState(''); const [elevation, setElevation] = useState(''); const [difficulty, setDifficulty] = useState<Difficulty>('moderate'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!loading && !session) navigate('/auth/sign-in'); }, [loading, navigate, session]);
  function undoPoint() { setPoints((current) => current.slice(0, -1)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (points.length < 2) { setMessage('Поставь на карте минимум две точки маршрута.'); return; } setBusy(true); setMessage(''); try { const id = await createRoute({ title, description, points, elevationGain: Number(elevation) || 0, difficulty, region }); navigate(`/routes/${id}`); } catch { setMessage('Не удалось сохранить маршрут. Попробуй ещё раз.'); } finally { setBusy(false); } }
  return <PageShell><main className="cycle-page new-route-page"><header className="page-heading"><div><p className="kicker">Новый трек</p><h1>Нарисуй дорогу.</h1><p>Кликай по карте — линия соберётся из точек. Дистанцию считаем автоматически.</p></div></header><div className="route-builder"><section><RoutePlannerMap points={points} onAdd={(point) => setPoints((current) => [...current, point])} /><div className="map-toolbar"><span>{points.length} точек · {routeDistanceKm(points).toFixed(1)} км</span><button className="quiet-button" onClick={undoPoint} disabled={!points.length}>Убрать последнюю</button></div></section><section className="form-card"><p className="kicker">Детали</p><h2>Расскажи про маршрут</h2><form className="cycle-form" onSubmit={(event) => void submit(event)}><label>Название<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Петля до Медеу" maxLength={120} /></label><label>Регион<input value={region} onChange={(event) => setRegion(event.target.value)} placeholder="Алматы" maxLength={80} /></label><label>Сложность<select value={difficulty} onChange={(event) => setDifficulty(event.target.value as Difficulty)}><option value="easy">Лёгкий</option><option value="moderate">Средний</option><option value="hard">Сложный</option></select></label><label>Набор высоты, м<input type="number" min="0" value={elevation} onChange={(event) => setElevation(event.target.value)} /></label><label>Описание<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Покрытие, вода, на что обратить внимание" maxLength={1000} /></label><button className="signal-button" disabled={busy}>{busy ? 'Сохраняем…' : 'Опубликовать маршрут'}</button></form>{message && <p className="form-note" role="alert">{message}</p>}</section></div></main></PageShell>;
}
