import { useState, type FormEvent } from 'react';
import { Link, useLocation } from 'wouter';
import { signUpWithEmail, startGoogleSignIn } from '../lib/auth';
import { useLocaleText } from '../lib/localized';
import { isSupabaseConfigured, supabase } from '../lib/supabase';

export function AuthForm({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const t = useLocaleText();
  const [, navigate] = useLocation(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const isSignup = mode === 'sign-up';
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (password.length < 8) { setMessage(t('Пароль должен быть не короче 8 символов.', 'Құпиясөз кемінде 8 таңбадан тұруы керек.', 'Password must be at least 8 characters.')); return; } setBusy(true); setMessage(''); try { const { data, error } = await (isSignup ? signUpWithEmail(email, password) : supabase.auth.signInWithPassword({ email, password })); if (error) { setMessage(t('Не удалось войти. Проверь почту и пароль.', 'Кіру мүмкін болмады. Пошта мен құпиясөзді тексер.', 'Could not sign in. Check your email and password.')); return; } if (isSignup && !data.session) { navigate(`/auth/confirm?email=${encodeURIComponent(email)}`); return; } navigate(isSignup ? '/onboarding' : '/dashboard'); } catch { setMessage(t('Не удалось подключиться к аккаунту. Попробуй ещё раз.', 'Аккаунтқа қосылу мүмкін болмады. Қайта көр.', 'Could not connect to your account. Try again.')); } finally { setBusy(false); } }
  async function google() { setBusy(true); setMessage(''); try { const { data, error } = await startGoogleSignIn(); if (error || !data.url) { setMessage(error?.message.includes('provider is not enabled') ? t('Вход через Google пока не подключён.', 'Google арқылы кіру әлі қосылмаған.', 'Google sign-in is not enabled yet.') : t('Не удалось открыть Google.', 'Google ашылмады.', 'Could not open Google.')); return; } window.location.assign(data.url); } catch { setMessage(t('Не удалось открыть Google.', 'Google ашылмады.', 'Could not open Google.')); } finally { setBusy(false); } }
  if (!isSupabaseConfigured) return <main className="auth-page"><section className="auth-card"><h1>{t('Supabase ещё не подключён', 'Supabase әлі қосылмаған', 'Supabase is not connected yet')}</h1><p>{t('Добавь настройки окружения, чтобы запустить сообщество.', 'Қауымдастықты іске қосу үшін орта параметрлерін қос.', 'Add environment settings to launch the community.')}</p></section></main>;
  return <section className="auth-card"><p className="kicker">Slipstream</p><h1>{isSignup ? t('Начни свой путь.', 'Өз жолыңды баста.', 'Start your journey.') : t('С возвращением.', 'Қайта келгеніңе қуаныштымыз.', 'Welcome back.')}</h1><p>{t('Твой гараж, твои километры и дороги рядом.', 'Сенің гаражың, километрлерің және жақын жолдар.', 'Your garage, your kilometres and nearby roads.')}</p><form className="cycle-form" onSubmit={(event) => void submit(event)}><label>{t('Электронная почта', 'Электрондық пошта', 'Email')}<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>{t('Пароль', 'Құпиясөз', 'Password')}<input type="password" required minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="signal-button" disabled={busy}>{busy ? t('Подождём…', 'Күте тұрыңыз…', 'Please wait…') : isSignup ? t('Создать аккаунт', 'Аккаунт жасау', 'Create account') : t('Войти', 'Кіру', 'Sign in')}</button></form><div className="auth-separator">{t('или', 'немесе', 'or')}</div><button className="outline-button" disabled={busy} onClick={() => void google()}>{t('Продолжить с Google', 'Google арқылы жалғастыру', 'Continue with Google')}</button>{message && <p className="form-note" role="alert">{message}</p>}<p className="auth-switch">{isSignup ? t('Уже есть аккаунт?', 'Аккаунтың бар ма?', 'Already have an account?') : t('Впервые здесь?', 'Мұнда алғаш ретсің бе?', 'New here?')} <Link href={isSignup ? '/auth/sign-in' : '/auth/sign-up'}>{isSignup ? t('Войти', 'Кіру', 'Sign in') : t('Создать аккаунт', 'Аккаунт жасау', 'Create account')}</Link></p></section>;
}
